//
//  BlackMistFilter.swift
//  Celluloid
//
//  Custom CIFilter using Metal kernel for Black Pro-Mist effect
//

import CoreImage
import os.log

private let logger = Logger(subsystem: "com.jakespurlock.Celluloid", category: "BlackMistFilter")

/// A custom CIFilter that emulates a Tiffen Black Pro-Mist filter effect
/// using a Metal kernel for GPU-accelerated processing.
///
/// The effect creates soft highlight bloom, reduced micro-contrast, and maintains rich blacks,
/// similar to the classic cinematic diffusion filter.
///
/// When the Metal kernel is available, this filter combines 5 operations into a single GPU pass.
/// Falls back to CIFilter chain if the kernel cannot be loaded.
class BlackMistFilter: CIFilter {

    // MARK: - Input Parameters

    @objc dynamic var inputImage: CIImage?

    /// Strength of the mist effect (0.0 - 1.0). Default: 0.5
    @objc dynamic var inputStrength: CGFloat = 0.5

    /// Blur radius for the diffusion. Default: 12.0
    @objc dynamic var inputBlurRadius: CGFloat = 12.0

    /// Exposure boost for highlights (EV). Default: 0.30
    @objc dynamic var inputExposureBoost: CGFloat = 0.30

    /// Final contrast adjustment. Default: 0.95
    @objc dynamic var inputContrast: CGFloat = 0.95

    /// Final brightness adjustment. Default: 0.02
    @objc dynamic var inputBrightness: CGFloat = 0.02

    /// Final saturation adjustment. Default: 1.02
    @objc dynamic var inputSaturation: CGFloat = 1.02

    // MARK: - Metal Kernel

    /// Compiled Metal blend kernel (lazy initialization)
    private static var blendKernel: CIBlendKernel? = {
        // Try to load the "default.metallib" file from the app bundle (auto-generated by Xcode when compiling Metal shaders)
        guard let url = Bundle.main.url(forResource: "default", withExtension: "metallib"),
              let data = try? Data(contentsOf: url) else {
            logger.error("Could not load default.metallib")
            return nil
        }

        do {
            let kernel = try CIBlendKernel(functionName: "blackMistBlend", fromMetalLibraryData: data)
            logger.info("Metal kernel loaded successfully")
            return kernel
        } catch {
            logger.error("Failed to create kernel: \(error)")
            return nil
        }
    }()

    // MARK: - Filter Output

    override var outputImage: CIImage? {
        guard let input = inputImage else { return nil }

        // Step 1: Create blurred version using CIGaussianBlur
        // (Gaussian blur requires multiple texture samples, best left to CI's optimized version)
        guard let blurFilter = CIFilter(name: "CIGaussianBlur") else { return input }
        blurFilter.setValue(input, forKey: kCIInputImageKey)
        blurFilter.setValue(inputBlurRadius, forKey: kCIInputRadiusKey)
        guard let blurred = blurFilter.outputImage?.cropped(to: input.extent) else { return input }

        // Step 2: Apply the Metal blend kernel if available
        if let kernel = BlackMistFilter.blendKernel {
            // Use the Metal kernel - combines 5 operations into 1 GPU pass
            if let result = kernel.apply(extent: input.extent,
                                         arguments: [input, blurred,
                                                    Float(inputStrength),
                                                    Float(inputExposureBoost),
                                                    Float(inputContrast),
                                                    Float(inputBrightness),
                                                    Float(inputSaturation)]) {
                return result
            }
        }

        // Fallback: Use CIFilter chain if Metal kernel not available
        return applyFallbackFilterChain(input: input, blurred: blurred)
    }

    // MARK: - Fallback Implementation

    /// Fallback implementation using standard CIFilters (same result, more GPU passes)
    private func applyFallbackFilterChain(input: CIImage, blurred: CIImage) -> CIImage? {
        // 1. Lift the blurred layer (bloom the highlights)
        guard let exposureFilter = CIFilter(name: "CIExposureAdjust") else { return input }
        exposureFilter.setValue(blurred, forKey: kCIInputImageKey)
        exposureFilter.setValue(inputExposureBoost, forKey: kCIInputEVKey)
        guard let brightBlur = exposureFilter.outputImage else { return input }

        // 2. Blend with soft light
        guard let blendFilter = CIFilter(name: "CISoftLightBlendMode") else { return input }
        blendFilter.setValue(brightBlur, forKey: kCIInputImageKey)
        blendFilter.setValue(input, forKey: kCIInputBackgroundImageKey)
        guard let misty = blendFilter.outputImage else { return input }

        // 3. Mix base + mist using alpha mask
        let maskColor = CIColor(red: 1, green: 1, blue: 1, alpha: inputStrength)
        guard let maskGen = CIFilter(name: "CIConstantColorGenerator") else { return input }
        maskGen.setValue(maskColor, forKey: kCIInputColorKey)
        guard let mask = maskGen.outputImage?.cropped(to: input.extent) else { return input }

        guard let mixFilter = CIFilter(name: "CIBlendWithAlphaMask") else { return input }
        mixFilter.setValue(misty, forKey: kCIInputImageKey)
        mixFilter.setValue(input, forKey: kCIInputBackgroundImageKey)
        mixFilter.setValue(mask, forKey: kCIInputMaskImageKey)
        guard let mixed = mixFilter.outputImage else { return input }

        // 4. Final color controls
        guard let controls = CIFilter(name: "CIColorControls") else { return mixed }
        controls.setValue(mixed, forKey: kCIInputImageKey)
        controls.setValue(inputContrast, forKey: kCIInputContrastKey)
        controls.setValue(inputBrightness, forKey: kCIInputBrightnessKey)
        controls.setValue(inputSaturation, forKey: kCIInputSaturationKey)

        return controls.outputImage?.cropped(to: input.extent) ?? mixed
    }

    // MARK: - Filter Attributes

    override var attributes: [String: Any] {
        return [
            kCIAttributeFilterDisplayName: "Black Mist",
            kCIAttributeFilterCategories: [kCICategoryStylize, kCICategoryVideo, kCICategoryStillImage],
            "inputStrength": [
                kCIAttributeDefault: 0.5,
                kCIAttributeMin: 0.0,
                kCIAttributeMax: 1.0,
                kCIAttributeType: kCIAttributeTypeScalar
            ],
            "inputBlurRadius": [
                kCIAttributeDefault: 12.0,
                kCIAttributeMin: 0.0,
                kCIAttributeMax: 100.0,
                kCIAttributeType: kCIAttributeTypeScalar
            ],
            "inputExposureBoost": [
                kCIAttributeDefault: 0.30,
                kCIAttributeMin: -2.0,
                kCIAttributeMax: 2.0,
                kCIAttributeType: kCIAttributeTypeScalar
            ],
            "inputContrast": [
                kCIAttributeDefault: 0.95,
                kCIAttributeMin: 0.5,
                kCIAttributeMax: 1.5,
                kCIAttributeType: kCIAttributeTypeScalar
            ],
            "inputBrightness": [
                kCIAttributeDefault: 0.02,
                kCIAttributeMin: -0.5,
                kCIAttributeMax: 0.5,
                kCIAttributeType: kCIAttributeTypeScalar
            ],
            "inputSaturation": [
                kCIAttributeDefault: 1.02,
                kCIAttributeMin: 0.0,
                kCIAttributeMax: 2.0,
                kCIAttributeType: kCIAttributeTypeScalar
            ]
        ]
    }
}
